# Generated by Django 5.0.1 on 2024-01-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_files_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[("doc", "Document"), ("img", "Image"), ("vid", "Video")],
                default="doc",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
